// The 64 colours of the classic Crayola 64-count box.
// Hex values follow the commonly published Crayola reference values.
const CRAYOLA_64 = [
  { name: "Red", hex: "#EE204D" },
  { name: "Scarlet", hex: "#FC2847" },
  { name: "Maroon", hex: "#C8385A" },
  { name: "Mahogany", hex: "#CD4A4A" },
  { name: "Chestnut", hex: "#BC5D58" },
  { name: "Red Orange", hex: "#FF5349" },
  { name: "Bittersweet", hex: "#FD7C6E" },
  { name: "Burnt Sienna", hex: "#EA7E5D" },
  { name: "Burnt Orange", hex: "#FF7F49" },
  { name: "Orange", hex: "#FF7538" },
  { name: "Tan", hex: "#FAA76C" },
  { name: "Raw Sienna", hex: "#D68A59" },
  { name: "Sepia", hex: "#A5694F" },
  { name: "Brown", hex: "#B4674D" },
  { name: "Tumbleweed", hex: "#DEAA88" },
  { name: "Macaroni and Cheese", hex: "#FFBD88" },
  { name: "Peach", hex: "#FFCFAB" },
  { name: "Apricot", hex: "#FDD9B5" },
  { name: "Yellow Orange", hex: "#FFB653" },
  { name: "Goldenrod", hex: "#FCD975" },
  { name: "Dandelion", hex: "#FDDB6D" },
  { name: "Yellow", hex: "#FCE883" },
  { name: "Green Yellow", hex: "#F0E891" },
  { name: "Spring Green", hex: "#ECEABE" },
  { name: "Olive Green", hex: "#BAB86C" },
  { name: "Yellow Green", hex: "#C5E384" },
  { name: "Asparagus", hex: "#87A96B" },
  { name: "Granny Smith Apple", hex: "#A8E4A0" },
  { name: "Forest Green", hex: "#6DAE81" },
  { name: "Green", hex: "#1CAC78" },
  { name: "Sea Green", hex: "#9FE2BF" },
  { name: "Shamrock", hex: "#45CEA2" },
  { name: "Robin's Egg Blue", hex: "#1FCECB" },
  { name: "Turquoise Blue", hex: "#77DDE7" },
  { name: "Blue Green", hex: "#0D98BA" },
  { name: "Pacific Blue", hex: "#1CA9C9" },
  { name: "Cerulean", hex: "#1DACD6" },
  { name: "Cornflower", hex: "#9ACEEB" },
  { name: "Navy Blue", hex: "#1974D2" },
  { name: "Blue", hex: "#1F75FE" },
  { name: "Midnight Blue", hex: "#1A4876" },
  { name: "Cadet Blue", hex: "#B0B7C6" },
  { name: "Periwinkle", hex: "#C5D0E6" },
  { name: "Indigo", hex: "#5D76CB" },
  { name: "Blue Violet", hex: "#7366BD" },
  { name: "Purple Mountains' Majesty", hex: "#9D81BA" },
  { name: "Violet (Purple)", hex: "#926EAE" },
  { name: "Wisteria", hex: "#CDA4DE" },
  { name: "Plum", hex: "#8E4585" },
  { name: "Fuchsia", hex: "#C364C5" },
  { name: "Orchid", hex: "#E6A8D7" },
  { name: "Red Violet", hex: "#C0448F" },
  { name: "Wild Strawberry", hex: "#FF43A4" },
  { name: "Tickle Me Pink", hex: "#FC89AC" },
  { name: "Carnation Pink", hex: "#FFAACC" },
  { name: "Lavender", hex: "#FCB4D5" },
  { name: "Mauvelous", hex: "#EF98AA" },
  { name: "Salmon", hex: "#FF9BAA" },
  { name: "Melon", hex: "#FDBCB4" },
  { name: "White", hex: "#FFFFFF" },
  { name: "Timberwolf", hex: "#DBD7D2" },
  { name: "Gray", hex: "#95918C" },
  { name: "Outer Space", hex: "#414A4C" },
  { name: "Black", hex: "#000000" },
];
